### ISSUE TITLE
编译出错问题,src/main.c:13:10: fatal error: xtutil.h: No such file or directory

### ISSUE THREAD

**Issue by xacn-ma** [YuzukiHD/FreeRTOS-HIFI4-DSP#3]
你好!
1)编译FreeRTOS-HIFI4-DSP时提示src/main.c:13:10: fatal error: xtutil.h: No such file or directory没有找到,把对应用到的文件中注释掉,编译可以通过(系统Debian10).这不影响系统的运行吧!
2)在这个系统中是否可以调用FFT,IFFT,FIR,IIR这些函数,后期有没有实现的计划.
3)如有可能能否加个好朋友,我也有需求在HIFI4-DSP上进行产品开发,微信:13554907706. 谢谢!

**Comment by nickfox-taterli** [comment]
你这都编译失败了,怎么可能可以运行呢?我怀疑是包含库有问题,xtutil.h听起来是xtensa里的东西,另外怎么用起来呢,都没说怎么load程序.国内就是资料堪忧得多,东一块西一块得.

**Comment by xacn-ma** [comment]
我把引用xtuil.h的注释后,编译通过,在./build目录下生成了dsp.elf文件.大小是:129K左右.

**Comment by YuzukiTsuru** [comment]
1. 可以删了，在上层引用了
2. 这个是自己适配的，非官方不支持TIE与加速指令，可以当一个小MCU用
3. 加载程序源码：https://github.com/YuzukiHD/FreeRTOS-HIFI4-DSP/tree/master/host/uboot-driver/dsp ，是一个uboot驱动
