### ISSUE TITLE
uboot 加载 dsp.elf 报错

### ISSUE THREAD

**Issue by xyq1113723547** [YuzukiHD/FreeRTOS-HIFI4-DSP#4]
开发板是 Sipeed Lichee RV，系统镜像是 `LicheeRV_Tina_dock_hdmi_8723ds.img` ，利用了 Tina Linux 中魔改的 uboot，其中包括了 bootr 命令来给 DSP 加载 firmware。

## uboot 命令行下加载 firmware 报错
```
=> echo $(boot_dsp0)
sunxi_flash read 45000000 ${dsp0_partition};bootr 45000000 0 0
=> sunxi_flash read 45000000 ${dsp0_partition};bootr 45000000 0 0
dsp0:uart config fail
dsp0:gpio init config fail
dsp0:find section err
```

## 修改 bootdelay
在 /etc/fw_env.config 中添加 `/dev/by-name/env` `/dev/by-name/env-redund` 
之后通过 `fw_setenv` 编辑 bootdelay

## 制作 dsp 分区

`dd if=dsp.elf of=/dev/mmcblk0p5`

**Comment by YuzukiTsuru** [comment]
设备树内没配置dsp相关参数，启核失败

**Comment by xyq1113723547** [comment]
是 FreeRTOS 的设备树吗？
我看了 https://github.com/100askTeam/NezaD1_u-boot-2018/blob/master/drivers/dsp/sun20iw1/dsp.c#L129
`uart config fail` `gpio init config fail` `find section err` 都在 `sunxi_dsp_init` 函数里

**Comment by YuzukiTsuru** [comment]
是uboot的设备树，描述了dsp核心分配的uart，io，还有efl解析地址，入口地址等

另外在适配linux下的remoteproc驱动之后可以使用linux的rproc框架启动dsp
